import Foundation
import Testing

@testable import Permafrost

@Suite struct PasteboardCapturePolicyTests {
    private func input(
        types: Set<String> = ["public.utf8-plain-text"],
        isPaused: Bool = false,
        isExcludedApp: Bool = false,
        recordConcealed: Bool = false
    ) -> PasteboardCapturePolicy.Input {
        PasteboardCapturePolicy.Input(
            types: types,
            isPaused: isPaused,
            isExcludedApp: isExcludedApp,
            recordConcealed: recordConcealed
        )
    }

    @Test func normalContentCaptures() {
        let decision = PasteboardCapturePolicy.decide(input())
        #expect(decision == .capture(concealed: false))
    }

    @Test func pausedCaptureSkips() {
        let decision = PasteboardCapturePolicy.decide(input(isPaused: true))
        #expect(decision == .skip(.paused))
    }

    @Test func excludedAppSkips() {
        let decision = PasteboardCapturePolicy.decide(input(isExcludedApp: true))
        #expect(decision == .skip(.excludedApp))
    }

    @Test func concealedContentSkipsByDefault() {
        let decision = PasteboardCapturePolicy.decide(
            input(types: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"]))
        #expect(decision == .skip(.concealedNotOptedIn))
    }

    @Test func concealedContentAllowedWhenOptedIn() {
        let decision = PasteboardCapturePolicy.decide(
            input(
                types: ["org.nspasteboard.ConcealedType", "public.utf8-plain-text"],
                recordConcealed: true))
        #expect(decision == .capture(concealed: true))
    }

    @Test func transientTypeSkips() {
        let decision = PasteboardCapturePolicy.decide(
            input(types: ["org.nspasteboard.TransientType"]))
        #expect(decision == .skip(.transient))
    }

    @Test func autoGeneratedTypeSkips() {
        let decision = PasteboardCapturePolicy.decide(
            input(types: ["org.nspasteboard.AutoGeneratedType"]))
        #expect(decision == .skip(.transient))
    }

    @Test func pauseTakesPriorityOverOtherSkipReasons() {
        let decision = PasteboardCapturePolicy.decide(
            input(
                types: ["org.nspasteboard.ConcealedType"],
                isPaused: true,
                isExcludedApp: true))
        #expect(decision == .skip(.paused))
    }
}
