import AppKit
import PermafrostCore

/// Polls NSPasteboard.changeCount (ADR-004 — there is no notification API).
/// The idle cost is one integer compare every 0.3 s.
@MainActor
final class PasteboardWatcher {
    var onCapture: (ClipboardCapture) -> Void = { _ in }

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    private static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    private static let concealedType = "org.nspasteboard.ConcealedType"

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            // Timer fires on the main run loop.
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        if !types.isDisjoint(with: Self.transientTypes) { return }

        let concealed = types.contains(Self.concealedType)
        if concealed && !AppSettings.shared.recordConcealed { return }

        guard let capture = makeCapture(from: pasteboard, types: types, concealed: concealed)
        else { return }
        Log.capture.debug("captured \(capture.kind.rawValue, privacy: .public) item")
        onCapture(capture)
    }

    private func makeCapture(
        from pasteboard: NSPasteboard, types: Set<String>, concealed: Bool
    ) -> ClipboardCapture? {
        let sourceApp = NSWorkspace.shared.frontmostApplication?.localizedName

        // Copied files: store their paths as text rather than Finder's icon images.
        if types.contains("public.file-url"),
            let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
            !urls.isEmpty
        {
            let paths = urls.map(\.path).joined(separator: "\n")
            return ClipboardCapture(text: paths, sourceApp: sourceApp, isConcealed: concealed)
        }

        // Images next — screen snips (⌃⇧⌘4) arrive as PNG or TIFF. Normalize to PNG.
        for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type.rawValue) {
            guard let data = pasteboard.data(forType: type) else { continue }
            let png = type == .png ? data : Thumbnailer.pngData(normalizing: data)
            guard let png else { continue }
            guard png.count <= AppSettings.shared.maxImageBytes else {
                Log.capture.info("skipped oversized image (\(png.count) bytes)")
                return nil
            }
            return ClipboardCapture(imageData: png, sourceApp: sourceApp, isConcealed: concealed)
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let rich = pasteboard.data(forType: .rtf)
            return ClipboardCapture(
                text: text, richData: rich, sourceApp: sourceApp, isConcealed: concealed)
        }
        return nil
    }
}
