import AppKit
import PermafrostCore

/// Whether a pasteboard change should be captured, and why not when it's skipped
/// (BACKLOG item 12). Takes only plain values — no `NSPasteboard`/`NSWorkspace` — so
/// it can be unit tested the way `PanelPasteServing` let `PanelModel` be tested
/// without AppKit.
struct PasteboardCapturePolicy {
    struct Input {
        var types: Set<String>
        var isPaused: Bool
        var isExcludedApp: Bool
        var recordConcealed: Bool
    }

    enum Decision: Equatable {
        case capture(concealed: Bool)
        case skip(SkipReason)
    }

    enum SkipReason: Equatable {
        case paused
        case transient
        case excludedApp
        case concealedNotOptedIn
    }

    static let transientTypes: Set<String> = [
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
    ]
    static let concealedType = "org.nspasteboard.ConcealedType"

    /// Order matches the prior inline checks in `PasteboardWatcher.poll()`: pause,
    /// then transient/auto-generated types, then excluded app, then concealed opt-in.
    static func decide(_ input: Input) -> Decision {
        guard !input.isPaused else { return .skip(.paused) }
        guard input.types.isDisjoint(with: transientTypes) else { return .skip(.transient) }
        guard !input.isExcludedApp else { return .skip(.excludedApp) }
        let concealed = input.types.contains(concealedType)
        if concealed && !input.recordConcealed { return .skip(.concealedNotOptedIn) }
        return .capture(concealed: concealed)
    }
}

/// Polls NSPasteboard.changeCount (ADR-004 — there is no notification API).
/// The idle cost is one integer compare every 0.3 s.
@MainActor
final class PasteboardWatcher {
    var onCapture: (ClipboardCapture) -> Void = { _ in }

    private var timer: Timer?
    private var lastChangeCount = NSPasteboard.general.changeCount

    func start() {
        guard timer == nil else { return }
        let timer = Timer(timeInterval: 0.3, repeats: true) { [weak self] _ in
            // Timer fires on the main run loop.
            MainActor.assumeIsolated { self?.poll() }
        }
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        timer?.invalidate()
        timer = nil
    }

    /// Call immediately after writing to `NSPasteboard.general` for an outgoing paste/copy
    /// (`PasteService`). Polling only compares `changeCount`, so without this it can't tell
    /// "the user copied something new" from "Permafrost itself just wrote the pasteboard to
    /// paste" — every paste bumps `changeCount` and gets re-captured as if it were incoming.
    /// That was invisible for a normal rich paste (the re-capture is bit-identical to what's
    /// already stored, so it just dedups against itself) but not for plain-text paste (found
    /// 2026-07-21): it deliberately writes less data than the stored item, so the re-capture
    /// hashed differently, was inserted as a distinct new item, and evicted the original
    /// rich item under the retention cap.
    func ignoreOwnWrite() {
        lastChangeCount = NSPasteboard.general.changeCount
    }

    private func poll() {
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChangeCount else { return }
        lastChangeCount = pasteboard.changeCount

        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        let frontmostApp = NSWorkspace.shared.frontmostApplication
        let input = PasteboardCapturePolicy.Input(
            types: types,
            isPaused: AppSettings.shared.capturePaused,
            isExcludedApp: AppSettings.shared.isExcluded(bundleID: frontmostApp?.bundleIdentifier),
            recordConcealed: AppSettings.shared.recordConcealed
        )

        let concealed: Bool
        switch PasteboardCapturePolicy.decide(input) {
        case .skip(.paused):
            Log.capture.debug("capture paused; skipped pasteboard change")
            return
        case .skip:
            return
        case .capture(let isConcealed):
            concealed = isConcealed
        }

        guard
            let capture = makeCapture(
                from: pasteboard, types: types, concealed: concealed,
                sourceApp: frontmostApp?.localizedName)
        else { return }
        Log.capture.debug("captured \(capture.kind.rawValue, privacy: .public) item")
        onCapture(capture)
    }

    private func makeCapture(
        from pasteboard: NSPasteboard, types: Set<String>, concealed: Bool, sourceApp: String?
    ) -> ClipboardCapture? {
        // Copied files: store their paths as text rather than Finder's icon images.
        if types.contains("public.file-url"),
            let urls = pasteboard.readObjects(forClasses: [NSURL.self]) as? [URL],
            !urls.isEmpty
        {
            let paths = urls.map(\.path).joined(separator: "\n")
            return ClipboardCapture(text: paths, sourceApp: sourceApp, isConcealed: concealed)
        }

        // Images next — screen snips (⌃⇧⌘4) arrive as PNG or TIFF. Normalize to PNG.
        for type in [NSPasteboard.PasteboardType.png, .tiff] where types.contains(type.rawValue) {
            guard let data = pasteboard.data(forType: type) else { continue }
            let png = type == .png ? data : Thumbnailer.pngData(normalizing: data)
            guard let png else { continue }
            guard png.count <= AppSettings.shared.maxImageBytes else {
                Log.capture.info("skipped oversized image (\(png.count) bytes)")
                return nil
            }
            return ClipboardCapture(imageData: png, sourceApp: sourceApp, isConcealed: concealed)
        }

        if let text = pasteboard.string(forType: .string), !text.isEmpty {
            let rich = pasteboard.data(forType: .rtf)
            return ClipboardCapture(
                text: text, richData: rich, sourceApp: sourceApp, isConcealed: concealed)
        }
        return nil
    }
}
